import type { UnicodeBlock } from './types';

export const customUnicodeBlocks: UnicodeBlock[] = [
  { name: 'Punctuation & Symbols', ranges: [['\u0020', '\u002F'], ['\u003A', '\u0040'], ['\u005B', '\u0060'], ['\u007B', '\u007E']] },
  { name: 'German', text: '€äöüÄÖÜß‚‘„“' },
  {
    name: 'Punctuation & Symbols Minimal',
    ranges: [['\u0020', '\u002F']],
    text: ':=?@€',
  },
];

export const unicodeBlocks: UnicodeBlock[] = [
  { name: 'Basic Latin', ranges: [['\u0000', '\u007F']] },
  { name: 'Latin-1 Supplement', ranges: [['\u0080', '\u00FF']] },
  { name: 'Latin Extended-A', ranges: [['\u0100', '\u017F']] },
  { name: 'Latin Extended-B', ranges: [['\u0180', '\u024F']] },
  { name: 'IPA Extensions', ranges: [['\u0250', '\u02AF']] },
  { name: 'Spacing Modifier Letters', ranges: [['\u02B0', '\u02FF']] },
  { name: 'Combining Diacritical Marks', ranges: [['\u0300', '\u036F']] },
  { name: 'Greek and Coptic', ranges: [['\u0370', '\u03FF']] },
  { name: 'Cyrillic', ranges: [['\u0400', '\u04FF']] },
  { name: 'Cyrillic Supplement', ranges: [['\u0500', '\u052F']] },
  { name: 'Armenian', ranges: [['\u0530', '\u058F']] },
  { name: 'Hebrew', ranges: [['\u0590', '\u05FF']] },
  { name: 'Arabic', ranges: [['\u0600', '\u06FF']] },
  { name: 'Syriac', ranges: [['\u0700', '\u074F']] },
  { name: 'Arabic Supplement', ranges: [['\u0750', '\u077F']] },
  { name: 'Thaana', ranges: [['\u0780', '\u07BF']] },
  { name: 'NKo', ranges: [['\u07C0', '\u07FF']] },
  { name: 'Samaritan', ranges: [['\u0800', '\u083F']] },
  { name: 'Mandaic', ranges: [['\u0840', '\u085F']] },
  { name: 'Syriac Supplement', ranges: [['\u0860', '\u086F']] },
  { name: 'Arabic Extended-B', ranges: [['\u0870', '\u089F']] },
  { name: 'Arabic Extended-A', ranges: [['\u08A0', '\u08FF']] },
  { name: 'Devanagari', ranges: [['\u0900', '\u097F']] },
  { name: 'Bengali', ranges: [['\u0980', '\u09FF']] },
  { name: 'Gurmukhi', ranges: [['\u0A00', '\u0A7F']] },
  { name: 'Gujarati', ranges: [['\u0A80', '\u0AFF']] },
  { name: 'Oriya', ranges: [['\u0B00', '\u0B7F']] },
  { name: 'Tamil', ranges: [['\u0B80', '\u0BFF']] },
  { name: 'Telugu', ranges: [['\u0C00', '\u0C7F']] },
  { name: 'Kannada', ranges: [['\u0C80', '\u0CFF']] },
  { name: 'Malayalam', ranges: [['\u0D00', '\u0D7F']] },
  { name: 'Sinhala', ranges: [['\u0D80', '\u0DFF']] },
  { name: 'Thai', ranges: [['\u0E00', '\u0E7F']] },
  { name: 'Lao', ranges: [['\u0E80', '\u0EFF']] },
  { name: 'Tibetan', ranges: [['\u0F00', '\u0FFF']] },
  { name: 'Myanmar', ranges: [['\u1000', '\u109F']] },
  { name: 'Georgian', ranges: [['\u10A0', '\u10FF']] },
  { name: 'Hangul Jamo', ranges: [['\u1100', '\u11FF']] },
  { name: 'Ethiopic', ranges: [['\u1200', '\u137F']] },
  { name: 'Ethiopic Supplement', ranges: [['\u1380', '\u139F']] },
  { name: 'Cherokee', ranges: [['\u13A0', '\u13FF']] },
  { name: 'Unified Canadian Aboriginal Syllabics', ranges: [['\u1400', '\u167F']] },
  { name: 'Ogham', ranges: [['\u1680', '\u169F']] },
  { name: 'Runic', ranges: [['\u16A0', '\u16FF']] },
  { name: 'Tagalog', ranges: [['\u1700', '\u171F']] },
  { name: 'Hanunoo', ranges: [['\u1720', '\u173F']] },
  { name: 'Buhid', ranges: [['\u1740', '\u175F']] },
  { name: 'Tagbanwa', ranges: [['\u1760', '\u177F']] },
  { name: 'Khmer', ranges: [['\u1780', '\u17FF']] },
  { name: 'Mongolian', ranges: [['\u1800', '\u18AF']] },
  { name: 'Unified Canadian Aboriginal Syllabics Extended', ranges: [['\u18B0', '\u18FF']] },
  { name: 'Limbu', ranges: [['\u1900', '\u194F']] },
  { name: 'Tai Le', ranges: [['\u1950', '\u197F']] },
  { name: 'New Tai Lue', ranges: [['\u1980', '\u19DF']] },
  { name: 'Khmer Symbols', ranges: [['\u19E0', '\u19FF']] },
  { name: 'Buginese', ranges: [['\u1A00', '\u1A1F']] },
  { name: 'Tai Tham', ranges: [['\u1A20', '\u1AAF']] },
  { name: 'Combining Diacritical Marks Extended', ranges: [['\u1AB0', '\u1AFF']] },
  { name: 'Balinese', ranges: [['\u1B00', '\u1B7F']] },
  { name: 'Sundanese', ranges: [['\u1B80', '\u1BBF']] },
  { name: 'Batak', ranges: [['\u1BC0', '\u1BFF']] },
  { name: 'Lepcha', ranges: [['\u1C00', '\u1C4F']] },
  { name: 'Ol Chiki', ranges: [['\u1C50', '\u1C7F']] },
  { name: 'Cyrillic Extended-C', ranges: [['\u1C80', '\u1C8F']] },
  { name: 'Georgian Extended', ranges: [['\u1C90', '\u1CBF']] },
  { name: 'Sundanese Supplement', ranges: [['\u1CC0', '\u1CCF']] },
  { name: 'Vedic Extensions', ranges: [['\u1CD0', '\u1CFF']] },
  { name: 'Phonetic Extensions', ranges: [['\u1D00', '\u1D7F']] },
  { name: 'Phonetic Extensions Supplement', ranges: [['\u1D80', '\u1DBF']] },
  { name: 'Combining Diacritical Marks Supplement', ranges: [['\u1DC0', '\u1DFF']] },
  { name: 'Latin Extended Additional', ranges: [['\u1E00', '\u1EFF']] },
  { name: 'Greek Extended', ranges: [['\u1F00', '\u1FFF']] },
  { name: 'General Punctuation', ranges: [['\u2000', '\u206F']] },
  { name: 'Superscripts and Subscripts', ranges: [['\u2070', '\u209F']] },
  { name: 'Currency Symbols', ranges: [['\u20A0', '\u20CF']] },
  { name: 'Combining Diacritical Marks for Symbols', ranges: [['\u20D0', '\u20FF']] },
  { name: 'Letterlike Symbols', ranges: [['\u2100', '\u214F']] },
  { name: 'Number Forms', ranges: [['\u2150', '\u218F']] },
  { name: 'Arrows', ranges: [['\u2190', '\u21FF']] },
  { name: 'Mathematical Operators', ranges: [['\u2200', '\u22FF']] },
  { name: 'Miscellaneous Technical', ranges: [['\u2300', '\u23FF']] },
  { name: 'Control Pictures', ranges: [['\u2400', '\u243F']] },
  { name: 'Optical Character Recognition', ranges: [['\u2440', '\u245F']] },
  { name: 'Enclosed Alphanumerics', ranges: [['\u2460', '\u24FF']] },
  { name: 'Box Drawing', ranges: [['\u2500', '\u257F']] },
  { name: 'Block Elements', ranges: [['\u2580', '\u259F']] },
  { name: 'Geometric Shapes', ranges: [['\u25A0', '\u25FF']] },
  { name: 'Miscellaneous Symbols', ranges: [['\u2600', '\u26FF']] },
  { name: 'Dingbats', ranges: [['\u2700', '\u27BF']] },
  { name: 'Miscellaneous Mathematical Symbols-A', ranges: [['\u27C0', '\u27EF']] },
  { name: 'Supplemental Arrows-A', ranges: [['\u27F0', '\u27FF']] },
  { name: 'Braille Patterns', ranges: [['\u2800', '\u28FF']] },
  { name: 'Supplemental Arrows-B', ranges: [['\u2900', '\u297F']] },
  { name: 'Miscellaneous Mathematical Symbols-B', ranges: [['\u2980', '\u29FF']] },
  { name: 'Supplemental Mathematical Operators', ranges: [['\u2A00', '\u2AFF']] },
  { name: 'Miscellaneous Symbols and Arrows', ranges: [['\u2B00', '\u2BFF']] },
  { name: 'Glagolitic', ranges: [['\u2C00', '\u2C5F']] },
  { name: 'Latin Extended-C', ranges: [['\u2C60', '\u2C7F']] },
  { name: 'Coptic', ranges: [['\u2C80', '\u2CFF']] },
  { name: 'Georgian Supplement', ranges: [['\u2D00', '\u2D2F']] },
  { name: 'Tifinagh', ranges: [['\u2D30', '\u2D7F']] },
  { name: 'Ethiopic Extended', ranges: [['\u2D80', '\u2DDF']] },
  { name: 'Cyrillic Extended-A', ranges: [['\u2DE0', '\u2DFF']] },
  { name: 'Supplemental Punctuation', ranges: [['\u2E00', '\u2E7F']] },
  { name: 'CJK Radicals Supplement', ranges: [['\u2E80', '\u2EFF']] },
  { name: 'Kangxi Radicals', ranges: [['\u2F00', '\u2FDF']] },
  { name: 'Ideographic Description Characters', ranges: [['\u2FF0', '\u2FFF']] },
  { name: 'CJK Symbols and Punctuation', ranges: [['\u3000', '\u303F']] },
  { name: 'Hiragana', ranges: [['\u3040', '\u309F']] },
  { name: 'Katakana', ranges: [['\u30A0', '\u30FF']] },
  { name: 'Bopomofo', ranges: [['\u3100', '\u312F']] },
  { name: 'Hangul Compatibility Jamo', ranges: [['\u3130', '\u318F']] },
  { name: 'Kanbun', ranges: [['\u3190', '\u319F']] },
  { name: 'Bopomofo Extended', ranges: [['\u31A0', '\u31BF']] },
  { name: 'CJK Strokes', ranges: [['\u31C0', '\u31EF']] },
  { name: 'Katakana Phonetic Extensions', ranges: [['\u31F0', '\u31FF']] },
  { name: 'Enclosed CJK Letters and Months', ranges: [['\u3200', '\u32FF']] },
  { name: 'CJK Compatibility', ranges: [['\u3300', '\u33FF']] },
  { name: 'CJK Unified Ideographs Extension A', ranges: [['\u3400', '\u4DBF']] },
  { name: 'Yijing Hexagram Symbols', ranges: [['\u4DC0', '\u4DFF']] },
  { name: 'CJK Unified Ideographs', ranges: [['\u4E00', '\u9FFF']] },
  { name: 'Yi Syllables', ranges: [['\uA000', '\uA48F']] },
  { name: 'Yi Radicals', ranges: [['\uA490', '\uA4CF']] },
  { name: 'Lisu', ranges: [['\uA4D0', '\uA4FF']] },
  { name: 'Vai', ranges: [['\uA500', '\uA63F']] },
  { name: 'Cyrillic Extended-B', ranges: [['\uA640', '\uA69F']] },
  { name: 'Bamum', ranges: [['\uA6A0', '\uA6FF']] },
  { name: 'Modifier Tone Letters', ranges: [['\uA700', '\uA71F']] },
  { name: 'Latin Extended-D', ranges: [['\uA720', '\uA7FF']] },
  { name: 'Syloti Nagri', ranges: [['\uA800', '\uA82F']] },
  { name: 'Common Indic Number Forms', ranges: [['\uA830', '\uA83F']] },
  { name: 'Phags-pa', ranges: [['\uA840', '\uA87F']] },
  { name: 'Saurashtra', ranges: [['\uA880', '\uA8DF']] },
  { name: 'Devanagari Extended', ranges: [['\uA8E0', '\uA8FF']] },
  { name: 'Kayah Li', ranges: [['\uA900', '\uA92F']] },
  { name: 'Rejang', ranges: [['\uA930', '\uA95F']] },
  { name: 'Hangul Jamo Extended-A', ranges: [['\uA960', '\uA97F']] },
  { name: 'Javanese', ranges: [['\uA980', '\uA9DF']] },
  { name: 'Myanmar Extended-B', ranges: [['\uA9E0', '\uA9FF']] },
  { name: 'Cham', ranges: [['\uAA00', '\uAA5F']] },
  { name: 'Myanmar Extended-A', ranges: [['\uAA60', '\uAA7F']] },
  { name: 'Tai Viet', ranges: [['\uAA80', '\uAADF']] },
  { name: 'Meetei Mayek Extensions', ranges: [['\uAAE0', '\uAAFF']] },
  { name: 'Ethiopic Extended-A', ranges: [['\uAB00', '\uAB2F']] },
  { name: 'Latin Extended-E', ranges: [['\uAB30', '\uAB6F']] },
  { name: 'Cherokee Supplement', ranges: [['\uAB70', '\uABBF']] },
  { name: 'Meetei Mayek', ranges: [['\uABC0', '\uABFF']] },
  { name: 'Hangul Syllables', ranges: [['\uAC00', '\uD7AF']] },
  { name: 'Hangul Jamo Extended-B', ranges: [['\uD7B0', '\uD7FF']] },
  { name: 'High Surrogates', ranges: [['\uD800', '\uDB7F']] },
  { name: 'High Private Use Surrogates', ranges: [['\uDB80', '\uDBFF']] },
  { name: 'Low Surrogates', ranges: [['\uDC00', '\uDFFF']] },
  { name: 'Private Use Area', ranges: [['\uE000', '\uF8FF']] },
  { name: 'CJK Compatibility Ideographs', ranges: [['\uF900', '\uFAFF']] },
  { name: 'Alphabetic Presentation Forms', ranges: [['\uFB00', '\uFB4F']] },
  { name: 'Arabic Presentation Forms-A', ranges: [['\uFB50', '\uFDFF']] },
  { name: 'Variation Selectors', ranges: [['\uFE00', '\uFE0F']] },
  { name: 'Vertical Forms', ranges: [['\uFE10', '\uFE1F']] },
  { name: 'Combining Half Marks', ranges: [['\uFE20', '\uFE2F']] },
  { name: 'CJK Compatibility Forms', ranges: [['\uFE30', '\uFE4F']] },
  { name: 'Small Form Variants', ranges: [['\uFE50', '\uFE6F']] },
  { name: 'Arabic Presentation Forms-B', ranges: [['\uFE70', '\uFEFF']] },
  { name: 'Halfwidth and Fullwidth Forms', ranges: [['\uFF00', '\uFFEF']] },
  { name: 'Specials', ranges: [['\uFFF0', '\uFFFF']] },
  { name: 'Linear B Syllabary', ranges: [['\u10000', '\u1007F']] },
  { name: 'Linear B Ideograms', ranges: [['\u10080', '\u100FF']] },
  { name: 'Aegean Numbers', ranges: [['\u10100', '\u1013F']] },
  { name: 'Ancient Greek Numbers', ranges: [['\u10140', '\u1018F']] },
  { name: 'Ancient Symbols', ranges: [['\u10190', '\u101CF']] },
  { name: 'Phaistos Disc', ranges: [['\u101D0', '\u101FF']] },
  { name: 'Lycian', ranges: [['\u10280', '\u1029F']] },
  { name: 'Carian', ranges: [['\u102A0', '\u102DF']] },
  { name: 'Coptic Epact Numbers', ranges: [['\u102E0', '\u102FF']] },
  { name: 'Old Italic', ranges: [['\u10300', '\u1032F']] },
  { name: 'Gothic', ranges: [['\u10330', '\u1034F']] },
  { name: 'Old Permic', ranges: [['\u10350', '\u1037F']] },
  { name: 'Ugaritic', ranges: [['\u10380', '\u1039F']] },
  { name: 'Old Persian', ranges: [['\u103A0', '\u103DF']] },
  { name: 'Deseret', ranges: [['\u10400', '\u1044F']] },
  { name: 'Shavian', ranges: [['\u10450', '\u1047F']] },
  { name: 'Osmanya', ranges: [['\u10480', '\u104AF']] },
  { name: 'Osage', ranges: [['\u104B0', '\u104FF']] },
  { name: 'Elbasan', ranges: [['\u10500', '\u1052F']] },
  { name: 'Caucasian Albanian', ranges: [['\u10530', '\u1056F']] },
  { name: 'Vithkuqi', ranges: [['\u10570', '\u105BF']] },
  { name: 'Linear A', ranges: [['\u10600', '\u1077F']] },
  { name: 'Latin Extended-F', ranges: [['\u10780', '\u107BF']] },
  { name: 'Cypriot Syllabary', ranges: [['\u10800', '\u1083F']] },
  { name: 'Imperial Aramaic', ranges: [['\u10840', '\u1085F']] },
  { name: 'Palmyrene', ranges: [['\u10860', '\u1087F']] },
  { name: 'Nabataean', ranges: [['\u10880', '\u108AF']] },
  { name: 'Hatran', ranges: [['\u108E0', '\u108FF']] },
  { name: 'Phoenician', ranges: [['\u10900', '\u1091F']] },
  { name: 'Lydian', ranges: [['\u10920', '\u1093F']] },
  { name: 'Meroitic Hieroglyphs', ranges: [['\u10980', '\u1099F']] },
  { name: 'Meroitic Cursive', ranges: [['\u109A0', '\u109FF']] },
  { name: 'Kharoshthi', ranges: [['\u10A00', '\u10A5F']] },
  { name: 'Old South Arabian', ranges: [['\u10A60', '\u10A7F']] },
  { name: 'Old North Arabian', ranges: [['\u10A80', '\u10A9F']] },
  { name: 'Manichaean', ranges: [['\u10AC0', '\u10AFF']] },
  { name: 'Avestan', ranges: [['\u10B00', '\u10B3F']] },
  { name: 'Inscriptional Parthian', ranges: [['\u10B40', '\u10B5F']] },
  { name: 'Inscriptional Pahlavi', ranges: [['\u10B60', '\u10B7F']] },
  { name: 'Psalter Pahlavi', ranges: [['\u10B80', '\u10BAF']] },
  { name: 'Old Turkic', ranges: [['\u10C00', '\u10C4F']] },
  { name: 'Old Hungarian', ranges: [['\u10C80', '\u10CFF']] },
  { name: 'Hanifi Rohingya', ranges: [['\u10D00', '\u10D3F']] },
  { name: 'Rumi Numeral Symbols', ranges: [['\u10E60', '\u10E7F']] },
  { name: 'Yezidi', ranges: [['\u10E80', '\u10EBF']] },
  { name: 'Old Sogdian', ranges: [['\u10F00', '\u10F2F']] },
  { name: 'Sogdian', ranges: [['\u10F30', '\u10F6F']] },
  { name: 'Old Uyghur', ranges: [['\u10F70', '\u10FAF']] },
  { name: 'Chorasmian', ranges: [['\u10FB0', '\u10FDF']] },
  { name: 'Elymaic', ranges: [['\u10FE0', '\u10FFF']] },
  { name: 'Brahmi', ranges: [['\u11000', '\u1107F']] },
  { name: 'Kaithi', ranges: [['\u11080', '\u110CF']] },
  { name: 'Sora Sompeng', ranges: [['\u110D0', '\u110FF']] },
  { name: 'Chakma', ranges: [['\u11100', '\u1114F']] },
  { name: 'Mahajani', ranges: [['\u11150', '\u1117F']] },
  { name: 'Sharada', ranges: [['\u11180', '\u111DF']] },
  { name: 'Sinhala Archaic Numbers', ranges: [['\u111E0', '\u111FF']] },
  { name: 'Khojki', ranges: [['\u11200', '\u1124F']] },
  { name: 'Multani', ranges: [['\u11280', '\u112AF']] },
  { name: 'Khudawadi', ranges: [['\u112B0', '\u112FF']] },
  { name: 'Grantha', ranges: [['\u11300', '\u1137F']] },
  { name: 'Newa', ranges: [['\u11400', '\u1147F']] },
  { name: 'Tirhuta', ranges: [['\u11480', '\u114DF']] },
  { name: 'Siddham', ranges: [['\u11580', '\u115FF']] },
  { name: 'Modi', ranges: [['\u11600', '\u1165F']] },
  { name: 'Mongolian Supplement', ranges: [['\u11660', '\u1167F']] },
  { name: 'Takri', ranges: [['\u11680', '\u116CF']] },
  { name: 'Ahom', ranges: [['\u11700', '\u1174F']] },
  { name: 'Dogra', ranges: [['\u11800', '\u1184F']] },
  { name: 'Warang Citi', ranges: [['\u118A0', '\u118FF']] },
  { name: 'Dives Akuru', ranges: [['\u11900', '\u1195F']] },
  { name: 'Nandinagari', ranges: [['\u119A0', '\u119FF']] },
  { name: 'Zanabazar Square', ranges: [['\u11A00', '\u11A4F']] },
  { name: 'Soyombo', ranges: [['\u11A50', '\u11AAF']] },
  { name: 'Unified Canadian Aboriginal Syllabics Extended-A', ranges: [['\u11AB0', '\u11ABF']] },
  { name: 'Pau Cin Hau', ranges: [['\u11AC0', '\u11AFF']] },
  { name: 'Bhaiksuki', ranges: [['\u11C00', '\u11C6F']] },
  { name: 'Marchen', ranges: [['\u11C70', '\u11CBF']] },
  { name: 'Masaram Gondi', ranges: [['\u11D00', '\u11D5F']] },
  { name: 'Gunjala Gondi', ranges: [['\u11D60', '\u11DAF']] },
  { name: 'Makasar', ranges: [['\u11EE0', '\u11EFF']] },
  { name: 'Lisu Supplement', ranges: [['\u11FB0', '\u11FBF']] },
  { name: 'Tamil Supplement', ranges: [['\u11FC0', '\u11FFF']] },
  { name: 'Cuneiform', ranges: [['\u12000', '\u123FF']] },
  { name: 'Cuneiform Numbers and Punctuation', ranges: [['\u12400', '\u1247F']] },
  { name: 'Early Dynastic Cuneiform', ranges: [['\u12480', '\u1254F']] },
  { name: 'Cypro-Minoan', ranges: [['\u12F90', '\u12FFF']] },
  { name: 'Egyptian Hieroglyphs', ranges: [['\u13000', '\u1342F']] },
  { name: 'Egyptian Hieroglyph Format Controls', ranges: [['\u13430', '\u1343F']] },
  { name: 'Anatolian Hieroglyphs', ranges: [['\u14400', '\u1467F']] },
  { name: 'Bamum Supplement', ranges: [['\u16800', '\u16A3F']] },
  { name: 'Mro', ranges: [['\u16A40', '\u16A6F']] },
  { name: 'Tangsa', ranges: [['\u16A70', '\u16ACF']] },
  { name: 'Bassa Vah', ranges: [['\u16AD0', '\u16AFF']] },
  { name: 'Pahawh Hmong', ranges: [['\u16B00', '\u16B8F']] },
  { name: 'Medefaidrin', ranges: [['\u16E40', '\u16E9F']] },
  { name: 'Miao', ranges: [['\u16F00', '\u16F9F']] },
  { name: 'Ideographic Symbols and Punctuation', ranges: [['\u16FE0', '\u16FFF']] },
  { name: 'Tangut', ranges: [['\u17000', '\u187FF']] },
  { name: 'Tangut Components', ranges: [['\u18800', '\u18AFF']] },
  { name: 'Khitan Small Script', ranges: [['\u18B00', '\u18CFF']] },
  { name: 'Tangut Supplement', ranges: [['\u18D00', '\u18D7F']] },
  { name: 'Kana Extended-B', ranges: [['\u1AFF0', '\u1AFFF']] },
  { name: 'Kana Supplement', ranges: [['\u1B000', '\u1B0FF']] },
  { name: 'Kana Extended-A', ranges: [['\u1B100', '\u1B12F']] },
  { name: 'Small Kana Extension', ranges: [['\u1B130', '\u1B16F']] },
  { name: 'Nushu', ranges: [['\u1B170', '\u1B2FF']] },
  { name: 'Duployan', ranges: [['\u1BC00', '\u1BC9F']] },
  { name: 'Shorthand Format Controls', ranges: [['\u1BCA0', '\u1BCAF']] },
  { name: 'Znamenny Musical Notation', ranges: [['\u1CF00', '\u1CFCF']] },
  { name: 'Byzantine Musical Symbols', ranges: [['\u1D000', '\u1D0FF']] },
  { name: 'Musical Symbols', ranges: [['\u1D100', '\u1D1FF']] },
  { name: 'Ancient Greek Musical Notation', ranges: [['\u1D200', '\u1D24F']] },
  { name: 'Mayan Numerals', ranges: [['\u1D2E0', '\u1D2FF']] },
  { name: 'Tai Xuan Jing Symbols', ranges: [['\u1D300', '\u1D35F']] },
  { name: 'Counting Rod Numerals', ranges: [['\u1D360', '\u1D37F']] },
  { name: 'Mathematical Alphanumeric Symbols', ranges: [['\u1D400', '\u1D7FF']] },
  { name: 'Sutton SignWriting', ranges: [['\u1D800', '\u1DAAF']] },
  { name: 'Latin Extended-G', ranges: [['\u1DF00', '\u1DFFF']] },
  { name: 'Glagolitic Supplement', ranges: [['\u1E000', '\u1E02F']] },
  { name: 'Nyiakeng Puachue Hmong', ranges: [['\u1E100', '\u1E14F']] },
  { name: 'Toto', ranges: [['\u1E290', '\u1E2BF']] },
  { name: 'Wancho', ranges: [['\u1E2C0', '\u1E2FF']] },
  { name: 'Ethiopic Extended-B', ranges: [['\u1E7E0', '\u1E7FF']] },
  { name: 'Mende Kikakui', ranges: [['\u1E800', '\u1E8DF']] },
  { name: 'Adlam', ranges: [['\u1E900', '\u1E95F']] },
  { name: 'Indic Siyaq Numbers', ranges: [['\u1EC70', '\u1ECBF']] },
  { name: 'Ottoman Siyaq Numbers', ranges: [['\u1ED00', '\u1ED4F']] },
  { name: 'Arabic Mathematical Alphabetic Symbols', ranges: [['\u1EE00', '\u1EEFF']] },
  { name: 'Mahjong Tiles', ranges: [['\u1F000', '\u1F02F']] },
  { name: 'Domino Tiles', ranges: [['\u1F030', '\u1F09F']] },
  { name: 'Playing Cards', ranges: [['\u1F0A0', '\u1F0FF']] },
  { name: 'Enclosed Alphanumeric Supplement', ranges: [['\u1F100', '\u1F1FF']] },
  { name: 'Enclosed Ideographic Supplement', ranges: [['\u1F200', '\u1F2FF']] },
  { name: 'Miscellaneous Symbols and Pictographs', ranges: [['\u1F300', '\u1F5FF']] },
  { name: 'Emoticons', ranges: [['\u1F600', '\u1F64F']] },
  { name: 'Ornamental Dingbats', ranges: [['\u1F650', '\u1F67F']] },
  { name: 'Transport and Map Symbols', ranges: [['\u1F680', '\u1F6FF']] },
  { name: 'Alchemical Symbols', ranges: [['\u1F700', '\u1F77F']] },
  { name: 'Geometric Shapes Extended', ranges: [['\u1F780', '\u1F7FF']] },
  { name: 'Supplemental Arrows-C', ranges: [['\u1F800', '\u1F8FF']] },
  { name: 'Supplemental Symbols and Pictographs', ranges: [['\u1F900', '\u1F9FF']] },
  { name: 'Chess Symbols', ranges: [['\u1FA00', '\u1FA6F']] },
  { name: 'Symbols and Pictographs Extended-A', ranges: [['\u1FA70', '\u1FAFF']] },
  { name: 'Symbols for Legacy Computing', ranges: [['\u1FB00', '\u1FBFF']] },
  { name: 'CJK Unified Ideographs Extension B', ranges: [['\u20000', '\u2A6DF']] },
  { name: 'CJK Unified Ideographs Extension C', ranges: [['\u2A700', '\u2B73F']] },
  { name: 'CJK Unified Ideographs Extension D', ranges: [['\u2B740', '\u2B81F']] },
  { name: 'CJK Unified Ideographs Extension E', ranges: [['\u2B820', '\u2CEAF']] },
  { name: 'CJK Unified Ideographs Extension F', ranges: [['\u2CEB0', '\u2EBEF']] },
  { name: 'CJK Compatibility Ideographs Supplement', ranges: [['\u2F800', '\u2FA1F']] },
  { name: 'CJK Unified Ideographs Extension G', ranges: [['\u30000', '\u3134F']] },
  { name: 'Tags', ranges: [['\uE0000', '\uE007F']] },
  { name: 'Variation Selectors Supplement', ranges: [['\uE0100', '\uE01EF']] },
];
